- hosts: localhost
  tasks:
    - filesystem:
        fstype: ext4
        dev: /dev/xvdb
      
    - mount:
        path: /var/www/html/
        src: /dev/xvdb
        fstype: ext4
        state: mounted
      
      
    - file:
        path: /var/www/html
        state: absent
      ignore_errors: yes
      
