- hosts: localhost
  tasks:
    - package:
        name: httpd
        state: present
        
    - service:
        name: httpd
        state: started
        enabled: yes
        
    - package:
        name: php
        state: present
 
    - package:
        name: git
        state: present
