- hosts: localhost
  tasks:
    - package:
        name: 
          - httpd
          - git
          - php
        state: present
        
    - service:
        name: httpd
        state: started
        enabled: yes
